@echo off
cls
color 02
echo You are not victim of the PETYA RANSOMWARE!
echo ________________________________________________________________________________________________________________________
echo.
echo The harddisks of your computer haven't been encrypted with an military grade
echo encryption algorithm. There is way to restore your data with nothing.
echo You dont purchase nothing. THIS IS A PARODY
echo.
echo THIS IS A PARODY NOTHING IS ENCRYPTED!!!:
echo.
echo 1. DONT DOWNLOAD NOTHING. THIS IS PARODY
echo 2. DONT VISIT PAGES THIS IS PARODY
echo 3. DONT ENTER YOUR PERSONAL DECRYPTION CODE
echo THIS IS A PARODY OF THE VIRUS
echo.
echo PRESS SPACE
pause > nul
MENU.BAT