@echo off
cls
color 0C
echo              uu$:$:$:$:$:$uu
echo          uu$$$$$$$$$$$$$$$$$$uu
echo         u$$$$$$$$$$$$$$$$$$$$$$u
echo         u$$$$$$$$$$$$$$$$$$$$$$$$u
echo        u$$$$$$$$$$$$$$$$$$$$$$$$$u
echo        u$$$$$$$$$$$$$$$$$$$$$$$$$u
echo        u$$$$$$*   *$$$*   *$$$$$$u
echo        *$$$$*      u$u       $$$$*
echo         $$$u       u$u       u$$$
echo         $$$u      u$$$u      u$$$
echo          *$$$$uu$$$   $$$uu$$$$*
echo           *$$$$$$$*   *$$$$$$$*
echo             u$$$$$$$u$$$$$$$u
echo              u$*$*$*$*$*$*$u
echo   uuu        $$u$ $ $ $ $u$$       uuu
echo  u$$$$        $$u$u$u$u$u$$       u$$$$
echo   $$$$$uu      *$$$$$$$$$*     uu$$$$$$
echo u$$$$$$$$$$$      *****    uuuu$$$$$$$$$
echo $$$$***$$$$$$$$$$uuu   uu$$$$$$$$$***$$$*
echo  ***      **$$$$$$$$$$$uu **$***
echo           uuuu **$$$$$$$$$$uuu
echo  u$$$uuu$$$$$$$$$uu **$$$$$$$$$$$uuu$$$
echo  $$$$$$$$$$****           **$$$$$$$$$$$*
echo    *$$$$$*                      **$$$$**
echo      $$$*     PRESS ANY KEY!      $$$$*
pause > nul
PETYA2.BAT