@echo off
cls
color F1
echo     FFFF                     PPPPPPPPPPPP   EEEEEEEEEEEE   RRRRRRRRRRRR   KKK   KKK   EEEEEEEEEEEE   LLL            
echo     FFFF                     PPPPPPPPPPPP   EEE            RRR      RRR   KKK  KKK    EEE            LLL                     
echo     FFFF                     PPP      PPP   EEE            RRR      RRR   KKK KKK     EEE            LLL                     
echo FFFFFFFFFFFFFFFFFFFF         PPP      PPP   EEE            RRRRRRRRRRRR   KKKKKK      EEE            LLL                     
echo FFFFFFFFFFFFFFFFFFFF         PPPPPPPPPPPP   EEEEEEEEEEEE   RRRR           KKKKKK      EEEEEEEEEEEE   LLL            
echo     FFFF                     PPPPPPPPPPPP   EEE            RR RR          KKK KKK     EEE            LLL                     
echo     FFFF                     PPP            EEE            RR  RR         KKK  KKK    EEE            LLL                     
echo     FFFF                     PPP            EEEEEEEEEEEE   RR   RR        KKK   KKK   EEEEEEEEEEEE   LLLLLLLLLLLL   
echo   EEEEEEEEEEEE
echo   EEE
echo   EEE
echo   EEE
echo   EEEEEEEEEEEE
echo   EEE
echo   EEE
echo   EEEEEEEEEEEE
echo you foud easterr egg
pause
menu.bat